language: java

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notification:
  email:
    recipients:
      - maxbirkin@gmail.com
    on_success: never
    on_failure: always
